path: /media/bruce/Documents/Ubuntu_ROS_files/文件资料/数据集/TUM_VI/dataset-corridor1_512_16/mav0
file_name: /media/bruce/Documents/Ubuntu_ROS_files/文件资料/数据集/TUM_VI/dataset-corridor1_512_16/mav0/cam0/data.csv

